title: Delta Method
tagline: Updates and Info about Delta Method
email: info@deltamethod.band
description: >- 
  This website was created as a demonstration for Jekyll custom theme
  named minimal-music-project. Its main feature is to make it easy to create
  websites for music projects
url: "https://www.deltamethod.band" # the base hostname & protocol for your site, e.g. http://example.com
author: deltamethod
twitter:
  username: deltamethodband
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  #- jekyll-paginate-v2
  - jekyll-paginate
# Build settings
markdown: kramdown
#remote_theme: ItsMeaga1n/minimal-music-project
remote_theme: ItsMeaga1n/minimal-categorized
permalink: /:title.html
pagination:
  enabled: true
  per_page: 4
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
